#!/usr/bin/env perl
use strict;
use warnings FATAL => 'all';
use utf8;
my $ticket_prefix = `git config  --get core.ticketprefix`;
chomp($ticket_prefix);
unless ($ticket_prefix) {
    warn "Please set core.ticketprefix to use this commitmsg hook.", "\n",
      "git config --add  core.ticketprefix 'MyOrg/MyTicketRepo'";
    exit 0;
}

my $commit_file = $ARGV[0] or die "no commit file specified!";
my $branch = `git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3 `;
chomp($branch);
my ($ticket) = $branch =~ m/ticket[-|_](\d+)/g;
exit(0) unless($ticket);
my $tagit = "$ticket_prefix#$ticket";

sub _has_ticket_info {
    open( my $in_fh, "<:encoding(UTF-8)", $commit_file ) or die "$@ $!";
    for (<$in_fh>) {
        return 1 if m|$tagit|g;
    }
    return 0;
}

if ( $ticket and !_has_ticket_info ) {
    open( my $fh, ">>:encoding(UTF-8)", $commit_file ) or die "$@ $!";
    print $fh $tagit, "\n";
    close($fh);
}
